pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
steps:
- script: |
    choco install ninja
    pip install conan
  displayName: Install Ninja, Conan
- script: mkdir build.debug
  displayName: 'Make build directory'
- task: CMake@1
  inputs:
    workingDirectory: 'build.debug'
    cmakeArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Debug ..'

- script: |
    cd build.debug
    ninja
  displayName: 'Run ninja, debug'
