trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
   
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: Docker@1
  inputs:
    containerRegistry: 'glaush-docker-repo'
    repository: 'glaush/juniorgram'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'