pool:
  vmImage: 'windows-latest'

steps:
- script: choco install ninja
  displayName: Install Ninja
- script: mkdir build.debug
  displayName: 'Make build directory'
- task: CMake@1
  inputs:
    workingDirectory: 'build.debug'
    cmakeArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Debug ..'

- script: |
    cd build.debug
    ninja
  displayName: 'Run ninja, debug'
