trigger:
  branches:
    include:
    - frontend-dev
  paths:
    exclude:
    - README.md
   
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'glaush-docker-repo'
    repository: 'glaush/juniorgram'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'