name: Build Docker image
on:
  workflow_dispatch:
jobs:
  build_and_push:
     runs-on: ubuntu-latest
   
     name: Build and Push Docker image to GitHub Packages
     steps:
     
      - name: Login to GitHub Packages Docker Registry.
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Check out the repo.
        uses: actions/checkout@v2
     
      - name: Build the image.
        run: docker build -t docker.pkg.github.com/f1nal3/juniorgram/juniorgram:stable .
    
      - name: Publish the image to GitHub Packages. 
        run: docker push docker.pkg.github.com/f1nal3/juniorgram/juniorgram:stable
