name: Continuous Delivery

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download juniorgram server artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: GCC Linux Build.yml
            workflow_conclusion: success
            branch: master
            event: push
            name: juniorgram-server
            
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host jg_host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.HOST_USER }}
          SSH_KEY: ${{ secrets.HOST_SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST_IP_ADDRESS }}
          
      - name: Stop JG Service
        run: |
          ssh jg_host 'sudo systemctl stop juniorgram.service '
          ssh jg_host 'sudo rm juniorgram' 
      
      - name: Upload server to Host
        run: scp Server.Exec $SSH_USER@$SSH_HOST:/home/jg_admin/juniorgram
        env:
          SSH_USER: ${{ secrets.HOST_USER }}
          SSH_HOST: ${{ secrets.HOST_IP_ADDRESS }}
        
      - name: Start JG Service
        run: |
          ssh jg_host 'sudo chmod +x juniorgram'
          ssh jg_host 'sudo systemctl start juniorgram.service'
