name: Linux GCC Release Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry.
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS }}
          
      - name: Pull docker image
        run: docker pull docker.pkg.github.com/f1nal3/juniorgram/juniorgram_linux:stable
        
      - name: Run Docker
        run: docker run -v "/home/runner/work/Juniorgram/Juniorgram":/Juniorgram docker.pkg.github.com/f1nal3/juniorgram/juniorgram_linux:stable /bin/sh -c "cd /Juniorgram && cmake . -DCMAKE_BUILD_TYPE=Release && cmake --build . && ctest --output-on-failure"
        
      - name: Archive server executable
        uses: actions/upload-artifact@v2
        with:
          name: juniorgram-server
          path: ./bin/Server.Exec

